--DROP TABLE IF EXISTS BOOKS;
--DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE IF NOT EXISTS AUTHORS(
    id INTEGER NOT NULL AUTO_INCREMENT,
    fullname VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS BOOKS(
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    title VARCHAR(128) NOT NULL,
    author_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) references AUTHORS(id)
);

COMMIT;

